title: Tecnual
description: Mr.Brown is a responsive jekyll theme
url: "https://tecnual.github.io" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog

# Comments
discus_identifier: tecnual

# Social settings
twitter_url: https://twitter.com/tecnual
facebook_url: https://facebook.com/tecnual
googleplus_url: https://plus.google.com/
instagram_url:
github_url: https://github.com/tecnual/
